Chat cosmetic change
VictorTennekes/transcendence pull request #15
Opened 2021-09-28 09:53 UTC by VictorTennekes

Made some visual changes to the chat like message formatting, adding a send icon and some color updates :)

<img width="382" alt="Screen Shot 2021-09-28 at 11 50 15 AM" src="https://user-images.githubusercontent.com/19930858/135065100-8eb4f31a-affe-40f1-8e3e-541c4120dcaf.png">

2021-09-28 10:37 UTC, saarikoski-jules requested changes
Looks awesome! There are two small changes I'd like to request:

- I don't think we need a package.json in the root of the project. If it's not needed, would you remove it?
- when a chat is a DM it doesn't have a name, so the chat messages will be hidden under the "home" symbol. Would you either add a name for DM's or make sure the name component will render space even when nameless.

Otherwise, great job!

2021-09-28 10:37 UTC, saarikoski-jules commented on package.json
> +{
I don't think we need this file?

2021-09-29 07:42 UTC, VictorTennekes commented
Should be fixed now :)

2021-09-29 09:09 UTC, saarikoski-jules approved these changes
wow you're defs the most hardworking one of us all

2021-09-29 09:10 UTC, merged